services:

  invoice-collector:
    image: invoice-collector:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
      - 9229:9229
    volumes:
      - ./src:/usr/app/src
      - ./locales:/usr/app/locales
      - ./views:/usr/app/views
      - ./env-output/.env.generated:/usr/app/.env.generated # Only for debug
    depends_on:
      - mongodb
    environment:
      - PORT=8080
      - REGISTRY_SERVER_ENDPOINT=https://registry.invoice-collector.com
      - DATABASE_URI=mongodb://mongodb:27017
      - DATABASE_MONGODB_NAME=dev
      - SECRET_MANAGER_TYPE=infisical
      - SECRET_MANAGER_INFISICAL_API_URI=http://infisical:8180
      - SECRET_MANAGER_INFISICAL_PROJECT_ID=${SECRET_MANAGER_INFISICAL_PROJECT_ID}
      - SECRET_MANAGER_INFISICAL_CLIENT_ID=${SECRET_MANAGER_INFISICAL_CLIENT_ID}
      - SECRET_MANAGER_INFISICAL_CLIENT_SECRET=${SECRET_MANAGER_INFISICAL_CLIENT_SECRET}
      - ENV=dev
    command: npm run debug
    entrypoint: ["/bin/sh", "-c", ". /usr/app/.env.generated && exec npm run debug"] # Only for debug

  mongodb:
    image : mongo:8.0.3
    container_name: mongodb
    volumes:
      - ./mongodb/data:/data/db
      - ./mongodb/config:/etc/mongo/      
      - ./media:/usr/app/media
      - ./test:/usr/app/test
    ports:
      - 27017:27017
    command: --logpath /dev/null
