name: "\U0001F916 New collector"
description: Support a new collector
title: "\U0001F916 [COLLECTOR] Collector name"
labels: collector
assignees: LucBerge
body:
  - type: input
    id: collector-name
    attributes:
      label: Name
      description: Name of the new collector
    validations:
      required: true
  - type: input
    id: collector-website
    attributes:
      label: Website
      description: Link to the website
      placeholder: https://...
    validations:
      required: true
  - type: input
    id: collector-invoices-url
    attributes:
      label: Invoices URL
      description: Link to the page where the invoices are listed (if applicable) or the API documentation
      placeholder: https://...
    validations:
      required: false
