name: Check OpenAPI spec

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'devscripts/swaggerConfig.js'
      - 'src/index.ts'
      - 'views/openapi/**'

jobs:
  test-openapi-spec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run openapi spec tests
        run: npm run test.cicd.openapi

  test-openapi-spec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Check for uncommited changes in OpenAPI
        run: |
          # Get current file hash before build
          before=$(sha256sum views/openapi/openapi.yml | awk '{ print $1 }')
          # Run build script to update openapi.yml
          node devscripts/build_openapi.js
          # Get file hash after build
          after=$(sha256sum views/openapi/openapi.yml | awk '{ print $1 }')
          # Check if the file has changed
          if [ "$before" != "$after" ]; then
            echo "openapi.yml has changed after build. Please commit the updated file:"
            echo "npm run build.openapi"
            echo "git add views/openapi/openapi.yml"
            echo "git commit -m 'Update openapi.yml'"
            exit 1
          fi
  
      - name: Check OpenAPI format
        uses: swaggerexpert/swagger-editor-validate@v1
        with:
          definition-file: views/openapi/openapi.yaml
    

